repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v14.0.0  # Replace this with the version of clang-format you want
    hooks:
      - id: clang-format
        args:
          - --style=file
          - --verbose
        files: \.(c|h)$  # Target only C source and header files
