repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v14.0.0
    hooks:
      - id: clang-format
        args:
          - --style=file
          - --verbose
        files: \.(c|h)$

  - repo: local
    hooks:
      - id: build-and-test
        name: Build and Run Unit Tests with ccache
        entry: |
          bash -c '
          # Ensure ccache is enabled
          export CC="ccache gcc"
          export CXX="ccache g++"

          # Prepare build directory
          mkdir -p build && cd build

          # Run cmake with ccache enabled
          cmake -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_C_COMPILER_LAUNCHER=ccache ..

          # Build with progress bar
          make -j$(nproc) --output-sync=target

          # Run unit tests
          ctest --output-on-failure

          # Show ccache stats
          ccache --show-stats
          '
        language: system
        always_run: true
        pass_filenames: false
        verbose: true
